### ISSUE TITLE
Package's lib directory is unavailable unless explicitly added to sources

### ISSUE THREAD

**Issue by lexaknyazev** [pulyaevskiy/node-interop#25] opened 2018-05-21 13:48 UTC
The example configuration in the readme (without `test` and `example`)
```yaml
targets:
  $default:
    sources:
      - "node/**"
```
fails with
```
$ pub run build_runner build --output node:build
[INFO] Generating build script completed, took 598ms
[INFO] Building new asset graph completed, took 617ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 4ms
[SEVERE] build_node_compilers|entrypoint on node/foo.dart:

Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'package:foo/foo.dart';` from foo|node/foo.dart at 1:1

[INFO] Running build completed, took 2.6s
[INFO] Caching finalized dependency graph completed, took 94ms
[SEVERE] Failed after 2.7s
```

Changing `build.yaml` to 
```yaml
targets:
  $default:
    sources:
      - "lib/**"
      - "node/**"
```
helps:
```
[INFO] Generating build script completed, took 578ms
[WARNING] Throwing away cached asset graph because the build phases have changed. This most commonly would happen as a result of adding a new dependency or updating your dependencies.
[INFO] Cleaning up outputs from previous builds. completed, took 11ms
[INFO] Reading cached asset graph completed, took 252ms
[INFO] Building new asset graph completed, took 562ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 4ms
[INFO] Running build completed, took 3.4s
[INFO] Caching finalized dependency graph completed, took 84ms
[INFO] Creating merged output dir `build` completed, took 9.1s
[INFO] Writing asset manifest completed, took 14ms
[INFO] Succeeded after 12.5s with 15 outputs (16 actions)
```

This is reproducible with both compilers.

**Comment by pulyaevskiy** [comment] 2019-09-15 01:26
I spent some time on this while upgrading to latest dependencies this week and I'm not sure why this doesn't work. The things I tried:

1. Adding `lib/**` to `targets.default.sources` in build_node_compilers
2. Adding `lib/**` to the entrypoint sources in builders configuration
3. A bunch of other combinations in different places throughout the code.

At this point I'm not sure where to look next. 

Interestingly enough, if I move entrypoints from `node/` folder to `web/` folder and delete `build.yaml` in a test project (so that it uses default config from build_node_compilers), then compiling works like a charm (provided I added `- web/**` to the entrypoint builder config at `defaults.generate_for.include`.

Will try and ping @jakemac53 and @natebosch : wondering if you could help in figuring out what I'm missing here?

**Comment by jakemac53** [comment] 2019-09-16 15:07
This is the expected behavior - the `default` target only applies to the package the `build.yaml` is in and so each user does have to have a custom `build.yaml` in order to include the `node` directory.

At the same time as soon as you configure the `sources` for that target you are overriding the normal defaults, so you have to fully specify all sources you care about (which is why you need `lib/**`). We don't have a way to express only adding a set of globs to the defaults.

The default sources include all the "standard" directories, which are derived from [this page](https://dart.dev/tools/pub/package-layout).

**Comment by jakemac53** [comment] 2019-09-16 15:10
Note that the `generate_for` configuration for the builder itself can only match a subset of the sources which is why adding it to there doesn't work.

**Comment by lexaknyazev** [comment] 2019-09-16 15:15
Is it reasonable to expect that `node/**` won't be among the default dirs? If so, the example and the description in the readme for `build_node_compilers` should be updated and this issue could be closed.

**Comment by jakemac53** [comment] 2019-09-16 15:29
We could consider adding it actually... I don't have a strong opinion here. We definitely don't want to include `node_modules` by default because it can get absolutely huge - but if I recall this `node` dir is just a convention for where to place your Dart app entrypoints that you want compiled to node js right?

**Comment by jakemac53** [comment] 2019-09-16 15:30
If we did add it we would likely want to update the package layout page as well, so that we can remain in sync with it.

**Comment by jakemac53** [comment] 2019-09-16 15:31
cc @natebosch wdyt, any reason not to add some more formal conventions and support for node compiled apps?

**Comment by lexaknyazev** [comment] 2019-09-16 15:38
> `node` dir is just a convention for where to place your Dart app entrypoints that you want compiled to node js right?

Yes.

> support for node compiled apps

As a stretch goal, a couple more steps could be considered here:
- Unification of `build*` infrastructure: for instance, `dart2js` glue is almost identical for `build_web_compilers` and `build_node_compilers`.
- Clean integration of `node_preamble` into `dart2js`. As of now, it's mostly a hack to "emulate" or polyfill certain symbols. It would be nice if `dart2js`-generated code was compatible with different environments out-of-the-box.

**Comment by jakemac53** [comment] 2019-09-16 15:50
cc @sigmundch for dart2js related things

**Comment by pulyaevskiy** [comment] 2019-09-16 16:48
> If we did add it we would likely want to update the package layout page as well, so that we can remain in sync with it.

This would be great. I think Node.js support kind of implicitly exist already, but it's not standardized, so having some basic guidelines would be really useful.

I just looked at `dart-sass` maintained by @nex3 package and I see that it uses `bin/` and conditional import for its entrypoint. It also implements its own build pipeline to compile into a Node compatible package. It would be nice if it could take advantage of build_runner workflow.

At the very least, it's a good use case to look at.

> * Unification of `build*` infrastructure: for instance, `dart2js` glue is almost identical for `build_web_compilers` and `build_node_compilers`.

I think this is a good conversation to have. We briefly touched on this when I just started on node compilers, but at that time we didn't have enough data to make any decision. There is now more information so we can probably resume this discussion.

**Comment by natebosch** [comment] 2019-09-16 17:28
> any reason not to add some more formal conventions and support for node compiled apps?

I have small concerns around adding documentation around node could convey that we have more support and expertise around node than we actually do within the team. On the whole, though, I'm in favor of making things easier and reducing boilerplate for more people so I think that's fine to do.

My preference would be to:
- Add `node/**` by default.
- Document conventions around package layout for node _here_, and not in Dart team owned docs.
- Add pointers to these docs from the build repo.

**Comment by pulyaevskiy** [comment] 2019-09-17 04:18
^ a good small step, so 👍 . Let me know if I can help in any way.

There is already a mention of this convention in the [README.md](https://github.com/pulyaevskiy/node-interop/tree/master/build_node_compilers) of build_node_compilers. I can probably emphasize it a bit more, so that there is less chance of users not noticing it.

**Comment by pulyaevskiy** [comment] 2020-05-12 04:35
Closing this as resolved.

**Closed as completed by pulyaevskiy** 2020-05-12 04:35 UTC
